brew uninstall 1password
brew uninstall adobe-creative-cloud
brew uninstall alfred
brew uninstall appcleaner
brew uninstall appcode
brew uninstall atom
brew uninstall bartender
brew uninstall bettertouchtool
brew uninstall biscuit
brew uninstall brackets
brew uninstall busycal
brew uninstall busycontacts
brew uninstall cleanmymac
brew uninstall clion
brew uninstall coda
brew uninstall codekit
brew uninstall contexts
brew uninstall dash
brew uninstall datagrip
brew uninstall default-folder-x
brew uninstall dropbox
brew uninstall firefox
brew uninstall goland
brew uninstall google-chrome
brew uninstall google-chrome-canary
brew uninstall google-drive-file-stream
brew uninstall grammarly
brew uninstall hyperdock
brew uninstall imagealpha
brew uninstall imageoptim
brew uninstall intellij-idea
brew uninstall iterm2
brew uninstall kaleidoscope
brew uninstall kawa
brew uninstall moom
brew uninstall mmhmm
brew uninstall notion
brew uninstall phpstorm
brew uninstall pycharm
brew uninstall resilio-sync
brew uninstall rider
brew uninstall rightfont
brew uninstall rubymine
brew uninstall slack
brew uninstall spectacle
brew uninstall spectrum
brew uninstall staruml
brew uninstall sublime-text
brew uninstall tableplus
brew uninstall telegram
brew uninstall tg-pro
brew uninstall tower
brew uninstall visual-studio-code
# brew cask install vmware-fusion
brew uninstall webstorm
brew uninstall zeplin
brew uninstall zoomus
